import Navbar from '@/components/Navbar';
import Tabs from '@/components/Tabs';
import Head from 'next/head';
import Image from 'next/image';
import BannerImage from '@/assets/banner.png';
import FooterImage from '@/assets/footer.jpg';
import Category from '@/components/Category';


export default function Home() {
  return (
    <>
      <Head>
        <title>视频流分类</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Tabs />
        <Image src={BannerImage} alt='banner' />
        <h2>热门</h2>
        <Category />

        <h2>直播</h2>
        <Category />

        <h2>推荐</h2>
        <Category />

        <Image src={FooterImage} alt='footer' />
        <footer><span>@Bilibili 2023</span></footer>
      </main>
    </>
  )
}
